---
- hosts: all
  user: root

  vars:
    tmpdir: /tmp
  tasks:
    - name: add repository
      yum: name=$item state=present
      with_items:
      - http://ftp.riken.jp/Linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - name: install python-pip
      yum: name=$item state=latest
      with_items:
        - gcc
        - python-devel
        - python-pip
    - name: install facric
      pip : name=fabric state=latest
