---
- hosts: all
  user: root

  vars:
    tmpdir: /tmp
  tasks:
    - name: add repository
      yum: name=$item state=present
      with_items:
      - http://ftp.riken.jp/Linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
